apiVersion: v1
kind: Secret
metadata:
  name: keycloak
  labels:
    app: keycloak
type: Opaque
data:
  KEYCLOAK_PASSWORD: YWRtaW4xMjM=
  DB_PASSWORD: a2V5Y2xvYWsxMjM=
stringData:
  KEYCLOAK_PASSWORD: admin123
  DB_PASSWORD: keycloak123
