kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
# use hostpath when deploying local k8s and use nas-thin for k8s cluster
  storageClassName: hostpath
  #  storageClassName: nas-thin
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
