apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  podSelector:
    matchLabels:
      app: keycloak
  policyTypes:
    - Ingress
  ingress:
    - ports:
        - protocol: TCP
          port: 8080
