apiVersion: v1
kind: Template
metadata:
  name: ${APPNAME}
  annotations:
    tags: "ngx-starter-kit-api,mongodb,template"
    description: ngx-starter-ki api template

objects:
- kind: Route
  apiVersion: v1
  metadata:
    name: ${APPNAME}
    labels:
      app: ${APPNAME}
  spec:
    to:
      kind: Service
      name: ${APPNAME}
    tls:
      termination: edge
    port:
      targetPort: ${APPNAME}-3000-http

- kind: Service
  apiVersion: v1
  metadata:
    name: ${APPNAME}
    labels:
      app: ${APPNAME}
  spec:
    ports:
    - name: ${APPNAME}-3000-http
      port: 3000
      protocol: TCP
      targetPort: 3000
    selector:
      app: ${APPNAME}

- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: ${APPNAME}
    labels:
      app: ${APPNAME}
  spec:
    replicas: 1
    strategy:
      type: Rolling
    triggers:
    - type: ConfigChange
    selector:
      app: ${APPNAME}
    template:
      metadata:
        name: ${APPNAME}
        labels:
          app: ${APPNAME}
          deploymentConfig: ${APPNAME}
      spec:
        containers:
        - name: ${APPNAME}
          image: ${DOCKERIMAGE}
          imagePullPolicy: Always
          resources:
            limits:
              memory: 4G
            requests:
              memory: 2G
          ports:
          - containerPort: 3000
            protocol: TCP
          env:
          - name: TYPEORM_HOST
            value: mongodb
          - name: TYPEORM_PORT
            value: 27017
          - name: TYPEORM_DATABASE
            value: cockpit
          - name: TYPEORM_USERNAME
            value: mdbuser
          - name: TYPEORM_PASSWORD
            value: cockpit123

parameters:
- name: APPNAME
  value: ngx-starter-kit-api
- name: DOCKERIMAGE
  value: xmlking/ngx-starter-kit-api:latest
